### ISSUE TITLE
Does your code really work? 

### ISSUE THREAD

**Issue by z2liudake** [ap229997/Conditional-Batch-Norm#11]
In the resnet.py, even your own test code cannot run correctly!!!  The parameters between  your defined functions cannot fit exactly!!! 
In the cbn.py. I don't konw why you init the self.beta and self.gamma to be 2 dimensions. What's more, you calculate the mean and var of the image across all elements.That's obviouslly wrong.

**Comment by ap229997** [comment]
I agree that there are a few bugs in the code. I haven't updated it in quite some time now.

Thanks for also pointing out the mean and var issue. You are right, I missed it in the code.

 You are welcome to create a pull request to resolve the bugs or I will update the code later.
