### ISSUE TITLE
MLPs for betas and gammas

### ISSUE THREAD

**Issue by jnhwkim** [ap229997/Conditional-Batch-Norm#3]
In https://github.com/ap229997/Conditional-Batch-Norm/blob/master/model/cbn.py#L30, 
doesn't CBN need separate MLPs to predict the deltas of betas and gammas? Otherwise, both deltas are the same.

**Comment by ap229997** [comment]
Yes, you are right. Thank you for pointing it out. I have must have missed it. There might be more such issues in the code. I will be updating the code soon or you can open a pull request and I will merge it.
