### ISSUE TITLE
Mean and variance over all the dimensions?

### ISSUE THREAD

**Issue by haoyangz** [ap229997/Conditional-Batch-Norm#5]
[These](https://github.com/ap229997/Conditional-Batch-Norm/blob/master/model/cbn.py#L103-L104) two lines in the CBN code calculates the mean and variance across all the dimensions. But shouldn't we calculate them for each channel separately ? (as per [here](http://gluon.mxnet.io/chapter04_convolutional-neural-networks/cnn-batch-norm-scratch.html))

**Comment by ap229997** [comment]
Yes, you are right. Thank you for reporting the error. I'll rectify the error or you can just open a PR and I'll merge it.
