### ISSUE TITLE
The inference of the model

### ISSUE THREAD

**Issue by WERush** [ap229997/Conditional-Batch-Norm#6]
Hi,

Can you point the inference process in your code? I do not find the inference code.

Thanks very much.

**Comment by ap229997** [comment]
I have added a basic structure for inference in the file inference.py though it's not complete. But I have added instructions wherever required which should be self-explanatory and sufficient. Do try once to get it working else I will upload the properly tested inference code in some time. If you are able to get it working, then just open a PR and I will merge the code.

**Comment by WERush** [comment]
How about the CBN? What is the difference in CBN between inference and training? Does the CBN just keep unchange during inference?

I do not see the `model.eval()` in your inference code.

**Comment by WERush** [comment]
In this [line](https://github.com/ap229997/Conditional-Batch-Norm/blob/master/model/cbn.py#L89), you initialize the gamma and beta with ones and zeros in each forward. Is it right? Can it make the learnable gamma and beta work well?

**Comment by WERush** [comment]
In my opinion, the initialization of gammas and betas should happen in the __init__() function rather than the forward() function. In your manner, the gammas and betas are always the ones or zeros, that does not make sense.

**Comment by ap229997** [comment]
Yes you are right. Good observation. The parameters should definitely be initialised in the init() function
