### ISSUE TITLE
gammas and betas 

### ISSUE THREAD

**Issue by 0zgur0** [ap229997/Conditional-Batch-Norm#8]
I think this variable should be 1-dimensional, gammas, and betas should be same over the batch, right?

https://github.com/ap229997/Conditional-Batch-Norm/blob/a7d234d4f7bf1c542030da645352ac3143c6fb12/model/cbn.py#L26

**Comment by ap229997** [comment]
Yes, as per equation 2 in the paper [Modulating early visual processing by language](https://papers.nips.cc/paper/7237-modulating-early-visual-processing-by-language.pdf), it varies only channel wise. Thanks for pointing out this error.
