### ISSUE TITLE
'TypeError: an integer is required (got type NoneType)'   

### ISSUE THREAD

**Issue by KyonP** [ap229997/Conditional-Batch-Norm#9]
https://github.com/ap229997/Conditional-Batch-Norm/blob/a7d234d4f7bf1c542030da645352ac3143c6fb12/model/cbn.py#L20

I have faced some errors around here.  'TypeError: an integer is required (got type NoneType)'   

Does `torch.zeros()` take None type?

**Comment by ap229997** [comment]
You need to provide them as arguments while initializing the model. I have updated the code. Thank you for pointing out the error.
